### PR TITLE
Expression simplified

### PR DESCRIPTION
**Pull request by xanadu-lee**
Simplify expressions to make them easier to read.

### CODE REVIEW

**Comment by rickmark** [comment]
Reject - first commits not squashed
second the expressions are not equivalent 

!(value > 0) is not the same as value == 0

**Comment by xanadu-lee** [comment]
I don't quite understand that it is not equivalent when the value of (size_t size) is.

**Comment by nikias** [comment]
From a compiler perspective @rickmark is correct, but in the end this shall prevent the size being passed to be <= 0. Now since the type is size_t it will not be considered < 0 anyway, so a check for == 0 is sufficient here.

**Comment by xanadu-lee** [comment]
Maybe I didn't see your preparation for the future code.
I saw size_t, so I modified it to look more intuitive.
If you think there is something wrong with my modification, I can close it.

**Pull request closed without merging**
